name: dhscanner-sast

on:
  push:
    branches:
      - master
jobs:
  run-dhscanner:
    runs-on: ubuntu-latest

    steps:
      - name: clone dhscanner (with submodules)
        run: |
          git clone --recurse-submodules https://github.com/OrenGitHub/dhscanner
          cd dhscanner && docker compose -f compose.rel.x64.yaml up -d
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0: ${{ secrets.APPROVED_URL_0 }}
      - name: checkout specific tag
        uses: actions/checkout@v4
        with:
          ref: '2024.3.1.dhscanner'

      - name: send healthcheck to dhscanner
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${APPROVED_BEARER_TOKEN_0}" \
            -H "Accept: application/json" \
            http://127.0.0.1:443/${APPROVED_URL_0_HEALTHCHECK}
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0_HEALTHCHECK: ${{ secrets.APPROVED_URL_0_HEALTHCHECK }}

      - name: test existence of .dhscanner.queries
        run: |
          cat .dhscanner.queries

      - name: send repo code to dhscanner
        run: |
          mkdir -p /tmp/oren
          tar -czf /tmp/oren/repo.tar.gz .
          curl -v -X POST \
            -H "Authorization: Bearer ${APPROVED_BEARER_TOKEN_0}" \
            -H "Content-Type: application/octet-stream" \
            -H "X-Directory-Name: sickchill" \
            -H "Ignore-Testing-Code: true" \
            --data-binary @repo.tar.gz \
            http://127.0.0.1:443/${APPROVED_URL_0}
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0: ${{ secrets.APPROVED_URL_0 }}
